### ISSUE TITLE
An expansion request

### ISSUE THREAD

**Issue by TomasHubelbauer** [joshwcomeau/waveforms#1]
Hey, thanks for this amazing presentation. I'd like to request an expansion to this paragraph:

> The difference is the scale. With harmonics, the additional "notes" are all multiples of the root frequency, whereas western music divides an octave into 12 intervals.

For me, this is the most intriguing aspect of it all, the transition from thinking about about time and displacement to thinking in terms of musical theory. I can't contribute anything on the topic myself, but if time allow and you find it worthwhile to expand this paragraph to perhaps its own section (not necessarily with another plot, just more explanation), that'd be much appreciated!

Thanks for considering.

**Comment by joshwcomeau** [comment]
hi @TomasHubelbauer!

Sorry it's taken me a bit to get back to you, been a hectic week!

Yeah, the chord thing at the end was an afterthought, like "oh I should explain how this relates to music", but it wasn't explored very fully since the thing was already so dang long.

I've been playing with the idea of a followup based around the idea of how music works in terms of sound; I think I'd rather make a second thing, rather than make the original thing even longer. Although truthfully I'm not likely to get to this anytime soon, a bunch of other stuff being juggled now.

Thanks for the feedback :)
